### ISSUE TITLE
 Little problem in README.md

### ISSUE THREAD

**Issue by zxxiao93** [kkentzo/pso.go#1]
```
settings.ObjectiveFunction = pso.Rosenbrock
```
type *pso.SwarmSettings has no field or method ObjectiveFunction.(ObjectiveFunction is a type)

It should be 
```
settings.Function = pso.Rosenbrock
```

Thank you for sharing your code! It is very helpful for me!

**Comment by kkentzo** [comment]
Of course, you're right. Thanks for pointing this out. [It's now been fixed](https://github.com/kkentzo/pso.go/commit/8104ac5362a9286a7903b6038499b61e2382a579) .
